# Generated by Django 5.0.1 on 2024-01-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_created", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="first_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="data_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
