# Generated by Django 5.0.1 on 2024-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_order_remove_customer_first_name_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField( 
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Out for delivery", "Out for delivery"),
                    ("Delivered", "Delivered"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Indoor", "Indoor"), ("Outdoor", "Outdoor")],
                max_length=100,
                null=True,
            ),
        ),
    ]
