# Generated by Django 5.0.1 on 2024-03-16 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_customer_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
    ]
