# Generated by Django 5.0.1 on 2024-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
